

# -------------------------------------------------------------- BirdGuess information list creation --------------------------------------------------------





# -----------------------------------------  Orden de los temas de bilinguismo dentro de cada elemento de la lista anidada ---------------------------------


#                                      * Nombre común en español
#                                      * Nombre común en inglés
#                                      * Nombre común en frances
#                                      * Nombre común en alemán
#                                      * Nombre común en chino mandarín (simplificado)
#                                      * Pinyin (Traducción fonética del idioma chino mandarín)
#                                      * Alimentación de la especie
#                                      * Estado de conservación


# ----------------------------------------------------------------------------------------------------------------------------------------------------------



BirdGuess_data = [["Elanus leucurus", "Elanio Coliblanco", "White-Tailed Kite", "Élanion à queue blanche", "Weißschwanz-Gleitaar", "白尾鸢", "Báiwěi yuān",
"Carnivore", "Least Concern"], ["Buteo platypterus", "Aguililla ala ancha", "Broad-Winged Hawk", "Petite Buse", "Breitflügelbussard", "巨翅鵟", "Jù chì kuáng",
"Carnivore: Small mammals and rodents", "Least Concern"], ["Rupornis magnirostris", "Busardo caminero", "Roadside Hawk", "Buse à gros bec", "Wegebussard",
"大嘴鵟", "Dà zuǐ kuáng", "Carnivore: insects, squamates and small mammals", "Least Concern"], ["Geranoaetus melanoleucus", "Águila Pechinegra",
"Black-chested Buzzard-Eagle", "Buse aguia", "Aguja", "鵟雕", "Kuáng diāo", "Carnivore: mid-sized mammals", "Least Concern"], ["Buteo brachyurus",
"Aguililla cola corta", "Short-tailed Hawk", "Buse à queue courte", "Kurzschwanzbussard", "短尾鵟", "Duǎn wěi kuáng", "Carnivore: small birds", "Least Concern"],
["Chondrohierax uncinatus", "Elanio Piquiganchudo", "Hook-billed Kite", "Milan bec-en-croc", "Langschnabelweih", "钩嘴鸢", "Gōu zuǐ yuān", 
"Carnivore: Tree snails", "Least Concern"], ["Buteogallus meridionalis", "Busardo sabanero", "Savanna Hawk", "Buse roussâtre", "Savannenbussard",
"草原鵟", "Cǎoyuán kuáng", "Carnivore: small mammals, small birds, lizards, snakes, toads, frogs, eels, other fish, crabs, roots, spiders, and large insects",
"Least Concern"], ["Geranospiza caerulescens", "Gavilán Zancón", "Crane Hawk", "Buse échasse", "Sperberweih", "鶴鷹", "Hè yīng", 
"Carnivore:  rodents, bats, lizards, snakes, frogs and small birds", "Least Concern"], ["Buteo swainsoni", "Aguililla de Swainson", "Swainson's Hawk",
"Buse de Swainson", "Präriebussard", "斯氏鵟", "Sī shì kuáng", "Carnivore", "Least Concern"], ["Geranoaetus albicaudatus", "Busardo coliblanco", 
"White-tailed Hawk", "Buse à queue blanche", "Weißschwanzbussard", "白尾鵟", "Báiwěi kuáng", "Carnivore: rabbits, lizzards, cotton, rats, snakes and frogs",
"Least Concern"], ["Buteo nitidus", "Aguililla gris", "Gray Hawk", "Buse cendrée", "Zweibindenbussard", "灰纹鵟", "Huī wén kuáng", "Carnivore: lizzards and snakes",
"Least Concern"], ["Buteo albigula", "Busardo gorjiblanco", "White-throated Hawk", "Buse à gorge blanche", "Weißkehlbussard", "白喉鵟", "Báihóu kuáng",
"Carnivore: insects, rodents, and birds", "Least Concern"], ["Buteo albonotatus", "Aguililla aura", "Zone-Tailed Hawk", "Buse à queue barrée", "Mohrenbussard",
"帶尾鵟", "Dài wěi kuáng", "Carnivore: small birds and mammals", "Least Concern"], ["Spizaetus tyrannus", "Águila Azor Negra", "Black Hawk-Eagle", "Aigle tyran",
"Tyrannenadler", "黑鹰雕", "Hēi yīng diāo", "Carnivore: large rodents (such as lowland pacas,squirrels), opossums and monkeys", "Least Concern"],
["Accipiter striatus", "Azor Americano", "Sharp-Shinned Hawk", "Epervier brun", "Eckschwanzsperber", "纹腹鹰", "Wén fù yīng", 
"Carnivore: small birds, especially various songbirds such as sparrows, wood-warblers, finches, wrens, nuthatches, tits, icterids and thrushes", 
"Least Concern"], ["Accipiter bicolor", "Azor Bicolor", "Bicolored Hawk", "Épervier bicolore", "Zweifarbensperber", "双色鹰", "Shuāngsè yīng", 
"Carnivore: smaller birds such as thrushes, mockingbirds and small doves", "Least Concern"], ["Parabuteo leucorrhous", "Busardo culiblanco", "White-rumped Hawk",
"Buse cul-blanc", "Weißbürzelbussard", "白腰鵟", "Bái yāo kuáng", "Carnivore: reptiles, frogs, insects, and rats", "Least Concern"], ["Ictinia mississippiensis",
"Elanio de Mississippi", "Mississippi Kite", "Milan du Mississippi", "Mississippi-Weihe", "密西西比灰鸢", "Mìxīxībǐ huī yuān", "Carnivore: insects", "Least Concern"],
["Ictinia plumbea", "Elanio Plomizo", "Plumbeous Kite", "Milan bleuâtre", "Schwebeweih", "南美灰鸢", "Nánměi huī yuān", "Carnivore: insects, snails, frogs",
"Least Concern"], ["Elanoides forficatus", "Elanio Tijereta", "American Swallow-Tailed Kite", "Milan à queue fourchue", "Schwalbenweih", "燕尾鸢",
"Yànwěi yuān", "Carnivore: reptiles, snakes and lizards", "Least Concern"], ["Rostrhamus sociabilis", "Caracolero común", "Snail Kite", "Milan des marais",
"Schneckenweih", "食螺鸢", "Shí luó yuān", "Carnivore: apple snails", "Least Concern"], ["Gampsonyx swainsonii", "Elanio Perla", "Pearl Kite", "Élanion perle",
"Perlaar", "娇鸢", "Jiāo yuān", "Carnivore: lizards, small birds, frogs and insects", "Least Concern"], ["Florisuga Mellivora", "Colibrí nuca blanca",
"White-necked Jacobin", "Colibri jacobin", "Jakobiner-Kolibri", "白颈蜂鸟", "Bái jǐng fēngniǎo", "Nectarivore", "Least Concern"], ["Eutoxeres aquila",
"Pico de Hoz Puntiblanco", "White-tipped Sicklebill", "Bec-en-faucille aigle", "Weißkehl-Sichelschnabel", "白尾尖镰嘴蜂鸟", "Báiwěi jiān lián zuǐ fēngniǎo",
"Nectarivore", "Least Concern"], ["Glaucis hirsutus", "Ermitaño Pechicanelo", "Rufous-breasted Hermit", "Ermite hirsute", "Rotschwanz-Schattenkolibri",
"棕胸铜色蜂鸟", "Zōng xiōng tóng sè fēngniǎo", "Nectarivore", "Least Concern"], ["Threnetes ruckeri", "Barbita Colibandeada", "Band-tailed Barbthroat",
"Ermite de Rücker", "Bindenschwanz-Eremit", "斑尾髭喉蜂鸟", "Bānwěi zī hóu fēngniǎo", "Nectarivore", "Least Concern"], ["Phaethornis striigularis",
"Ermitaño Golilistado", "Stripe-throated Hermit", "Ermite à gorge rayée", "Streifenkehl-Schattenkolibri", "纹喉隐蜂鸟", "Wén hóu yǐn fēngniǎo", 
"Nectarivore", "Least Concern"], ["Phaethornis griseogularis", "Ermitaño Barbigrís", "Gray-chinned Hermit", "Ermite à gorge grise", "Graukinn-Eremit",
"灰颏隐蜂鸟", "Huī kē yǐn fēngniǎo", "Nectarivore", "Least Concern"], ["Phaethornis augusti", "Ermitaño limpiacasa", "Sooty-capped Hermit", "Ermite dAuguste",
"Kappen-Eremit", "乌顶隐蜂鸟", "Wū dǐng yǐn fēngniǎo", "Nectarivore", "Least Concern"], ["Phaethornis anthophilus", "Ermitaño Carinegro", "Pale-bellied Hermit",
"Ermite anthophile", "Fahlbauch-Eremit", "淡腹隐蜂鸟", "Dàn fù yǐn fēngniǎo", "Nectarivore", "Least Concern"], ["Phaethornis guy", "Ermitaño Verde",
"Green Hermit", "Ermite vert", "Graubrust-Eremit", "绿隐蜂鸟", "Lǜ yǐn fēngniǎo", "Nectarivore", "Least Concern"], ["Phaethornis syrmatophorus",
"Ermitaño Ventrileonado", "Tawny-bellied Hermit", "Ermite à ventre fauve", "Orangebauch-Schattenkolibri", "茶腹隐蜂鸟", "Chá fù yǐn fēngniǎo", "Nectarivore",
"Least Concern"], ["Phaethornis longirostris", "Ermitaño Piquilargo", "Long-billed Hermit", "Ermite à longue queue", "Westlicher Langschwanz-Schattenkolibri", 
"西长尾隐蜂鸟", "Xī cháng wěi yǐn fēngniǎo", "Nectarivore", "Least Concern"], ["Doryfera ludovicae", "Colibrí picolanza mayor", "Green-fronted Lancebill",
"Porte-lance de Louise", "Grünstirn-Lanzettschnabel", "绿额矛嘴蜂鸟", "Lǜ é máo zuǐ fēngniǎo", "Nectarivore", "Least Concern"], ["Doryfera johannae",
"Colibrí picolanza menor", "Blue-fronted Lancebill", "Porte-lance de Jeanne", "Blaustirn-Lanzettschnabel", "蓝额矛嘴蜂鸟", "Lán é máo zuǐ fēngniǎo",
"Nectarivore", "Least Concern"], ["Schistes geoffroyi", "Colibrí picocuña oriental", "Geoffroy's Daggerbill", "Colibri de Geoffroy", "Östlicher Bunthalskolibri",
"楔嘴蜂鸟", "Xiē zuǐ fēngniǎo", "Nectarivore", "Least Concern"], ["Colibri delphinae", "Colibrí pardo", "Brown Violet-ear", "Colibri de Delphine",
"Brauner Veilchenohrkolibri", "褐紫耳蜂鸟", "Hè zǐ ěr fēngniǎo", "Nectarivore", "Least Concern"], ["Colibri thalassinus", "Colibrí oreja violeta",
"Green Violet-Ear", "Colibri thalassin", "Zwerg-Veilchenohr", "绿紫耳蜂鸟", "Lǜ zǐ ěr fēngniǎo", "Nectarivore", "Least Concern"], ["Colibri coruscans",
"Colibrí rutilante", "Sparkling Violetear", "Colibri anaïs", "Großer Veilchenohrkolibri", "辉紫耳蜂鸟", "Huī zǐ ěr fēngniǎo", "Nectarivore", 
"Least Concern"], ["Heliothryx barroti", "Colibrí hada occidental", "Purple-crowned Fairy", "Colibri féerique", "Purpurkron-Schmuckkolibri",
"紫冠仙蜂鸟", "Zǐ guān xiān fēngniǎo", "Nectarivore", "Least Concern"], ["Chrysolampis mosquitus", "Colibrí rubí", "Ruby Topaz", "Colibri rubis-topaze",
"Moskitokolibri", "金喉红顶蜂鸟", "Jīn hóu hóng dǐng fēngniǎo", "Nectarivore", "Least Concern"], ["Anthracothorax nigricollis", "Mango Gorginegro",
"Black-throated Mango", "Mango à cravate noire", "Schwarzbrust-Mangokolibri", "黑喉芒果蜂鸟", "Hēi hóu mángguǒ fēngniǎo", "Nectarivore", "Least Concern"],
["Heliangelus amethysticollis", "Colibrí gorjiamatista", "Amethyst-throated Sunangel", "Héliange de Clarisse", "Amethystsonnennymphe", "辉喉领蜂鸟",
"Huī hóu lǐng fēngniǎo", "Nectarivore", "Least Concern"], ["Heliangelus exortis", "Colibrí turmalina", "Tourmaline Sunangel", "Héliange tourmaline",
"Grünband-Sonnennymphe", "暗绿领蜂鸟", "Àn lǜ lǐng fēngniǎo", "Nectarivore", "Least Concern"], ["Discosura conversii", "Colicerda Verde", "Green Thorntail",
"Coquette à queue fine", "Grüne Fadenelfe", "绿刺尾蜂鸟", "Lǜ cì wěi fēngniǎo", "Nectarivore", "Least Concern"], ["Discosura popelairii", "Colicerda Crestuda",
"Wire-crested Thorntail", "Coquette de Popelaire", "Haubenfadenelfe", "翎冠刺尾蜂鸟", "Líng guān cì wěi fēngniǎo", "Nectarivore", "Least Concern"],
["Lophornis delattrei", "Coqueta Crestirrufa", "Rufous-crested Coquette", "Coquette de Delattre", "Rotschopfelfe", "棕冠蜂鸟", "Zōng guān fēngniǎo",
"Nectarivore", "Least Concern"], ["Lophornis stictolophus", "Coqueta Lentejuelada", "Spangled Coquette", "Coquette pailletée", "Glanzelfe", "斑冠蜂鸟",
"Bān guān fēngniǎo", "Nectarivore", "Least Concern"], ["Lophornis chalybeus", "Coqueta Festiva", "Festive Coquette", "Coquette chalybée", 
"Schmetterlingselfe", "极乐冠蜂鸟", "Jílè guān fēngniǎo", "Nectarivore", "Near Threatened"], ["Aglaiocercus kingii", "Silfo Colilargo", "Long-tailed Sylph",
"Sylphe à queue dazur", "Himmelssylve", "长尾蜂鸟", "Cháng wěi fēngniǎo", "Nectarivore", "Least Concern"], ["Adelomyia melanogenys", "Colibrí Jaspeado",
"Speckled Hummingbird", "Colibri moucheté", "Schwarzohrkolibri", "鳞斑蜂鸟", "Lín bān fēngniǎo", "Nectarivore", "Least Concern"], ["Lesbia victoriae",
"Colacintillo Colinegro", "Black-tailed Trainbearer", "Porte-traîne lesbie", "Schwarzschwanzsylphe", "黑带尾蜂鸟", "Hēi dài wěi fēngniǎo", "Nectarivore",
"Least Concern"], ["Lesbia nuna", "Colacintillo Coliverde", "Green-tailed Trainbearer", "Porte-traîne nouna", "Grünschwanzsylphe", "绿带尾蜂鸟",
"Lǜ dài wěi fēngniǎo", "Nectarivore", "Least Concern"], ["Ramphomicron microrhynchum", "Colibrí piquicorto común", "Purple-backed Thornbill",
"Colibri à petit bec", "Kleinschnabelkolibri", "紫背刺嘴蜂鸟", "Zǐ bèi cì zuǐ fēngniǎo", "Nectarivore", "Least Concern"], ["Chalcostigma heteropogon",
"Colibrí picoespina", "Bronze-tailed Thornbill", "Métallure à queue bronzée", "Bronzeglanzschwänzchen", "铜尾尖嘴蜂鸟", "Tóng wěi jiān zuǐ fēngniǎo",
"Nectarivore", "Least Concern"], ["Oxypogon guerinii", "Barbudito paramuno", "Bearded Helmetcrest", "Colibri casqué", "Grünbart-Helmkolibri",
"髯蜂鸟", "Rán fēngniǎo", "Nectarivore", "Least Concern"], ["Metallura tyrianthina", "Metalura Tiria", "Tyrian Metaltail", "Métallure émeraude",
"Smaragdkehl-Glanzschwänzchen", "紫辉尾蜂鸟", "Zǐ huī wěi fēngniǎo", "Nectarivore", "Least Concern"], ["Haplophaedia aureliae", "Calzadito verdoso norteño",
"Greenish Puffleg", "Érione dAurélie", "Bunthöschen", "淡绿蓬腿蜂鸟", "Dàn lǜ péng tuǐ fēngniǎo", "Nectarivore", "Least Concern"], ["Eriocnemis vestita",
"Calzadito reluciente", "Glowing Puffleg", "Érione pattue", "Violettkehl-Höschenkolibri", "紫颏毛腿蜂鸟", "Zǐ kē máo tuǐ fēngniǎo", "Nectarivore",
"Least Concern"], ["Eriocnemis cupreoventris", "Calzadito cobrizo", "Coppery-bellied Puffleg", "Érione à ventre cuivré", "Kupferbauch-Höschenkolibri",
"铜腹毛腿蜂鸟", "Tóng fù máo tuǐ fēngniǎo", "Nectarivore", "Near Threatened"], ["Eriocnemis aline", "Calzadito pechiblanco", "Emerald-bellied Puffleg",
"Érione dAline", "Weißbrust-Höschenkolibri", "翠腹毛腿蜂鸟", "Cuì fù máo tuǐ fēngniǎo", "Nectarivore", "Least Concern"], ["Aglaeactis cupripennis",
"Colibrí cobrizo", "Shining Sunbeam", "Colibri étincelant", "Rosenschillerkolibri", "闪羽蜂鸟", "Shǎn yǔ fēngniǎo", "Nectarivore", "Least Concern"],
["Coeligena coeligena", "Inca Bronceado", "Bronzy Inca", "Inca céleste", "Bronzeandenkolibri", "铜色星额蜂鸟", "Tóng sè xīng é fēngniǎo", "Nectarivore",
"Least Concern"], ["Coeligena prunellei", "Inca Negro", "Black Inca", "Inca noir", "Mohrenmusketier", "黑星额蜂鸟", "Hēi xīng é fēngniǎo", "Nectarivore",
"Vulnerable"], ["Coeligena torquata", "Inca Collarejo", "Collared Inca", "Inca à collier", "Krawattenmusketier", "领星额蜂鸟", "Lǐng xīng é fēngniǎo",
"Nectarivore", "Least Concern"], ["Coeligena bonapartei", "Inca Dorado", "Golden-bellied Starfrontlet", "Inca de Bonaparte", "Goldbauch-Andenkolibri",
"金腹星额蜂鸟", "Jīn fù xīng é fēngniǎo", "Nectarivore", "Least Concern"], ["Coeligena helianthea", "Inca ventrirrojo", "Blue-throated Starfrontlet",
"Inca porphyre", "Rosenbauch-Andenkolibri", "蓝喉星额蜂鸟", "Lán hóu xīng é fēngniǎo", "Nectarivore", "Least Concern"], ["Lafresnaya lafresnayi",
"Colibrí Terciopelo", "Mountain Velvetbreast", "Colibri de Lafresnaye", "Fadenschwingenkolibri", "绒胸蜂鸟", "Róng xiōng fēngniǎo", "Nectarivore",
"Least Concern"], ["Ensifera ensifera", "Colibrí Picoespada", "Sword-billed Hummingbird", "Colibri porte-épée", "Schwertschnabel", "剑嘴蜂鸟",
"Jiàn zuǐ fēngniǎo", "Nectarivore", "Least Concern"], ["Pterophanes cyanopterus", "Alazafiro Grande", "Great Sapphirewing", "Colibri à ailes saphir", 
"Blauflügelkolibri", "蓝翅大蜂鸟", "Lán chì dà fēngniǎo", "Nectarivore", "Least Concern"], ["Boissonneaua flavescens", "Colibrí colihabano", 
"Buff-tailed Coronet", "Colibri flavescent", "Fahlschwanzkolibri", "黄尾冕蜂鸟", "Huáng wěi miǎn fēngniǎo", "Nectarivore", "Least Concern"], 
["Ocreatus underwoodii", "Colaespátula Zamarrito", "Booted Racket-tail", "Haut-de-chausses à palettes", "Grünscheitel-Flaggensylphe", "盘尾蜂鸟",
"Pán wěi fēngniǎo", "Nectarivore", "Least Concern"], ["Heliodoxa rubinoides", "Brillante Pechianteado", "Fawn-breasted Brilliant", "Brillant rubinoïde",
"Braunbauch-Brillantkolibri", "棕胸辉蜂鸟", "Zōng xiōng huī fēngniǎo", "Nectarivore", "Least Concern"], ["Heliodoxa jacula", "Brillante Coroniverde",
"Green-crowned Brilliant", "Brillant fer-de-lance", "Grünscheitelbrillant", "绿顶辉蜂鸟", "Lǜ dǐng huī fēngniǎo", "Nectarivore", "Least Concern"], 
["Heliodoxa leadbeateri", "Brillante Frentivioleta", "Violet-fronted Brilliant", "Brillant à front violet", "Veilchenstirnbrillant", "紫额辉蜂鸟",
"Zǐ é huī fēngniǎo", "Nectarivore", "Least Concern"], ["Heliomaster longirostris", "Colibrí pico largo", "Long-billed Starthroat", "Colibri corinne",
"Rosenkehlchen", "长嘴星喉蜂鸟", "Cháng zuǐ xīng hóu fēngniǎo", "Nectarivore", "Least Concern"], ["Chaetocercus mulsant", "Colibrí de Mulsant",
"White-bellied Woodstar", "Colibri de Mulsant", "Weißbauchelfe", "白腹林蜂鸟", "Bái fù lín fēngniǎo", "Nectarivore", "Least Concern"], 
["Chaetocercus heliodor", "Colibrí de Heliodoro", "Gorgeted Woodstar", "Colibri héliodore", "Prachtkehlelfe", "粉髯林蜂鸟", "Fěn rán lín fēngniǎo",
"Nectarivore", "Least Concern"], ["Chlorostilbon gibsoni", "Esmeralda piquirroja", "Red-billed Emerald", "Émeraude de Gibson", "Gibsonsmaragdkolibri",
"红嘴翠蜂鸟", "Hóng zuǐ cuì fēngniǎo", "Nectarivore", "Least Concern"], ["Chlorostilbon mellisugus", "Esmeralda Coliazul", "Common Emerald", 
"Émeraude orvert", "Blauschwanz-Smaragdkolibri", "蓝尾翠蜂鸟", "Lán wěi cuì fēngniǎo", "Nectarivore", "Least Concern"], ["Chlorestes notata",
"Esmeralda gorjiazul", "Blue-chinned Sapphire", "Émeraude à menton bleu", "Blaukinn-Smaragdkolibri", "蓝颏青蜂鸟", "Lán kē qīng fēngniǎo", "Nectarivore",
"Least Concern"], ["Klais guimeti", "Colibrí Cabecivioleta", "Violet-headed Hummingbird", "Colibri à tête violette", "Violettkopfkolibri", "紫头蜂鸟",
"Zǐ tóu fēngniǎo", "Nectarivore", "Least Concern"], ["Campylopterus falcatus", "Ala de sable violeta", "Lazuline Sabrewing", "Campyloptère lazulite",
"Lasur-Säbelflügel", "棕尾刀翅蜂鸟", "Zōng wěi dāo chì fēngniǎo", "Nectarivore", "Least Concern"], ["Chalybura buffonii", "Calzonario de Buffon",
"White-vented Plumeleteer", "Colibri de Buffon", "Buffon-Kolibri", "白腹棕尾蜂鸟", "Bái fù zōng wěi fēngniǎo", "Nectarivore", "Least Concern"],
["Thalurania colombica", "Ninfa Coronada", "Crowned Woodnymph", "Dryade couronnée", "Violettkronennymphe", "蓝顶妍蜂鸟", "Lán dǐng yán fēngniǎo",
"Nectarivore", "Least Concern"], ["Thalurania furcata", "Ninfa Tijereta", "Fork-tailed Woodnymph", "Dryade à queue fourchue", "Schwalbennymphe",
"叉尾妍蜂鸟", "Chā wěi yán fēngniǎo", "Nectarivore", "Least Concern"], ["Amazilia tzacatl", "Amazilia Colirrufa", "Rufous-tailed Hummingbird",
"Ariane à ventre gris", "Braunschwanzamazilie", "棕尾蜂鸟", "Zōng wěi fēngniǎo", "Nectarivore", "Least Concern"], ["Amazilia versicolor", 
"Amazilia versicolor", "Versicolored Emerald", "Ariane versicolore", "Glanzamazilie", "虹彩蜂鸟", "Nectarivore", "Least Concern"], ["Amazilia franciae",
"Amazilia Andina", "Andean Emerald", "Ariane de Francia", "Andenamazilie", "安第斯蜂鸟", "Āndìsī fēngniǎo", "Nectarivore", "Least Concern"],
["Amazilia fimbriata", "Amazilia Gorgibrillante", "Glittering-throated Emerald", "Ariane de Linné", "Glitzeramazilie", "辉喉蜂鸟", "Huī hóu fēngniǎo",
"Nectarivore", "Least Concern"], ["Amazilia amabilis", "Amazilia Pechiazul", "Blue-chested Hummingbird", "Ariane aimable", "Blaubrustamazilie",
"蓝胸蜂鸟", "Lán xiōng fēngniǎo", "Nectarivore", "Least Concern"], ["Amazilia saucerottei", "Amazilia Coliazul", "Steely-vented Hummingbird",
"Ariane de Sophie", "Stahlamazilie", "灰腹蜂鸟", "Huī fù fēngniǎo", "Nectarivore", "Least Concern"], ["Amazilia cyanifrons", "Amazilia Ciáneo",
"Indigo-capped Hummingbird", "Ariane à front bleu", "Blaukappenamazilie", "青顶蜂鸟", "Qīng dǐng fēngniǎo", "Nectarivore", "Least Concern"],
["Amazilia viridigaster", "Amazilia colimorada", "Green-bellied Hummingbird", "Ariane à ventre vert", "Grünbauchamazilie", "绿腹蜂鸟", "Lǜ fù fēngniǎo",
"Nectarivore", "Least Concern"], ["Chrysuronia oenone", "Zafiro Colidorado", "Golden-tailed Sapphire", "Saphir œnone", "Bronzeschwanzsaphir",
"金尾蜂鸟", "Jīn wěi fēngniǎo", "Nectarivore", "Least Concern"], ["Lepidopyga goudoti", "Colibri de Goudot", "Shining-green Hummingbird", 
"Colibri de Goudot", "Goudot-Kolibri", "辉绿蜂鸟", "Huī lǜ fēngniǎo", "Nectarivore", "Least Concern"], ["Damophila julie", "Colibrí Ventrivioleta",
"Violet-bellied Hummingbird", "Colibri de Julie", "Julia-Kolibri", "紫腹蜂鸟", "Zǐ fù fēngniǎo", "Nectarivore", "Least Concern"]]